/*
Planera Resa

Sök och planera resor med Västtrafik

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel{}

// VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel Information about a journey trip leg.
type VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel struct {
	Origin VTApiPlaneraResaWebV4ModelsJourneysCallApiModel `json:"origin"`
	Destination VTApiPlaneraResaWebV4ModelsJourneysCallApiModel `json:"destination"`
	// Flag indicating if the trip leg is cancelled.
	IsCancelled bool `json:"isCancelled"`
	// Flag indicating if the trip leg is partially cancelled.
	IsPartCancelled *bool `json:"isPartCancelled,omitempty"`
	ServiceJourney *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel `json:"serviceJourney,omitempty"`
	// An ordered list (most important first) of notes related to the trip leg.
	Notes []VTApiPlaneraResaCoreModelsNote `json:"notes,omitempty"`
	// Estimated distance in meters. Only for transport mode Walk.
	EstimatedDistanceInMeters NullableInt32 `json:"estimatedDistanceInMeters,omitempty"`
	// The planned (according to timetable) connecting time in minutes relative to  the previous public transport trip leg (if any).
	PlannedConnectingTimeInMinutes NullableInt32 `json:"plannedConnectingTimeInMinutes,omitempty"`
	// The estimated (according to real-time data) connecting time in minutes relative to  the previous public transport trip leg (if any).
	EstimatedConnectingTimeInMinutes NullableInt32 `json:"estimatedConnectingTimeInMinutes,omitempty"`
	// Flag indicating that there is less than 5 minutes margin between arriving at the  origin stop point and the departure from that stop point.
	IsRiskOfMissingConnection NullableBool `json:"isRiskOfMissingConnection,omitempty"`
	// The planned departure time in RFC 3339 format.
	PlannedDepartureTime NullableString `json:"plannedDepartureTime,omitempty"`
	// The planned arrival time in RFC 3339 format.
	PlannedArrivalTime NullableString `json:"plannedArrivalTime,omitempty"`
	// The planned duration in minutes.
	PlannedDurationInMinutes NullableInt32 `json:"plannedDurationInMinutes,omitempty"`
	// The estimated departure time in RFC 3339 format, if available.
	EstimatedDepartureTime NullableString `json:"estimatedDepartureTime,omitempty"`
	// The estimated arrival time in RFC 3339 format, if available.
	EstimatedArrivalTime NullableString `json:"estimatedArrivalTime,omitempty"`
	// The estimated duration in minutes, if available.
	EstimatedDurationInMinutes NullableInt32 `json:"estimatedDurationInMinutes,omitempty"`
	// The best known time of the arrival in RFC 3339 format. Is EstimatedArrivalTime if exists, otherwise PlannedArrivalTime.
	EstimatedOtherwisePlannedArrivalTime NullableString `json:"estimatedOtherwisePlannedArrivalTime,omitempty"`
	// The best known time of the departure in RFC 3339 format. Is EstimatedDepartureTime if exists, otherwise PlannedDepartureTime.
	EstimatedOtherwisePlannedDepartureTime NullableString `json:"estimatedOtherwisePlannedDepartureTime,omitempty"`
	Occupancy *VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel `json:"occupancy,omitempty"`
	// Index of Leg in Journey
	JourneyLegIndex *int32 `json:"journeyLegIndex,omitempty"`
}

// NewVTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel instantiates a new VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel(origin VTApiPlaneraResaWebV4ModelsJourneysCallApiModel, destination VTApiPlaneraResaWebV4ModelsJourneysCallApiModel, isCancelled bool) *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel {
	this := VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel{}
	this.Origin = origin
	this.Destination = destination
	this.IsCancelled = isCancelled
	return &this
}

// NewVTApiPlaneraResaWebV4ModelsJourneysTripLegApiModelWithDefaults instantiates a new VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVTApiPlaneraResaWebV4ModelsJourneysTripLegApiModelWithDefaults() *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel {
	this := VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel{}
	return &this
}

// GetOrigin returns the Origin field value
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetOrigin() VTApiPlaneraResaWebV4ModelsJourneysCallApiModel {
	if o == nil {
		var ret VTApiPlaneraResaWebV4ModelsJourneysCallApiModel
		return ret
	}

	return o.Origin
}

// GetOriginOk returns a tuple with the Origin field value
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetOriginOk() (*VTApiPlaneraResaWebV4ModelsJourneysCallApiModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Origin, true
}

// SetOrigin sets field value
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetOrigin(v VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) {
	o.Origin = v
}

// GetDestination returns the Destination field value
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetDestination() VTApiPlaneraResaWebV4ModelsJourneysCallApiModel {
	if o == nil {
		var ret VTApiPlaneraResaWebV4ModelsJourneysCallApiModel
		return ret
	}

	return o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetDestinationOk() (*VTApiPlaneraResaWebV4ModelsJourneysCallApiModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Destination, true
}

// SetDestination sets field value
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetDestination(v VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) {
	o.Destination = v
}

// GetIsCancelled returns the IsCancelled field value
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetIsCancelled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsCancelled
}

// GetIsCancelledOk returns a tuple with the IsCancelled field value
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetIsCancelledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsCancelled, true
}

// SetIsCancelled sets field value
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetIsCancelled(v bool) {
	o.IsCancelled = v
}

// GetIsPartCancelled returns the IsPartCancelled field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetIsPartCancelled() bool {
	if o == nil || IsNil(o.IsPartCancelled) {
		var ret bool
		return ret
	}
	return *o.IsPartCancelled
}

// GetIsPartCancelledOk returns a tuple with the IsPartCancelled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetIsPartCancelledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPartCancelled) {
		return nil, false
	}
	return o.IsPartCancelled, true
}

// HasIsPartCancelled returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) HasIsPartCancelled() bool {
	if o != nil && !IsNil(o.IsPartCancelled) {
		return true
	}

	return false
}

// SetIsPartCancelled gets a reference to the given bool and assigns it to the IsPartCancelled field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetIsPartCancelled(v bool) {
	o.IsPartCancelled = &v
}

// GetServiceJourney returns the ServiceJourney field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetServiceJourney() VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel {
	if o == nil || IsNil(o.ServiceJourney) {
		var ret VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel
		return ret
	}
	return *o.ServiceJourney
}

// GetServiceJourneyOk returns a tuple with the ServiceJourney field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetServiceJourneyOk() (*VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel, bool) {
	if o == nil || IsNil(o.ServiceJourney) {
		return nil, false
	}
	return o.ServiceJourney, true
}

// HasServiceJourney returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) HasServiceJourney() bool {
	if o != nil && !IsNil(o.ServiceJourney) {
		return true
	}

	return false
}

// SetServiceJourney gets a reference to the given VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel and assigns it to the ServiceJourney field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetServiceJourney(v VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) {
	o.ServiceJourney = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetNotes() []VTApiPlaneraResaCoreModelsNote {
	if o == nil {
		var ret []VTApiPlaneraResaCoreModelsNote
		return ret
	}
	return o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetNotesOk() ([]VTApiPlaneraResaCoreModelsNote, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) HasNotes() bool {
	if o != nil && IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given []VTApiPlaneraResaCoreModelsNote and assigns it to the Notes field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetNotes(v []VTApiPlaneraResaCoreModelsNote) {
	o.Notes = v
}

// GetEstimatedDistanceInMeters returns the EstimatedDistanceInMeters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetEstimatedDistanceInMeters() int32 {
	if o == nil || IsNil(o.EstimatedDistanceInMeters.Get()) {
		var ret int32
		return ret
	}
	return *o.EstimatedDistanceInMeters.Get()
}

// GetEstimatedDistanceInMetersOk returns a tuple with the EstimatedDistanceInMeters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetEstimatedDistanceInMetersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.EstimatedDistanceInMeters.Get(), o.EstimatedDistanceInMeters.IsSet()
}

// HasEstimatedDistanceInMeters returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) HasEstimatedDistanceInMeters() bool {
	if o != nil && o.EstimatedDistanceInMeters.IsSet() {
		return true
	}

	return false
}

// SetEstimatedDistanceInMeters gets a reference to the given NullableInt32 and assigns it to the EstimatedDistanceInMeters field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetEstimatedDistanceInMeters(v int32) {
	o.EstimatedDistanceInMeters.Set(&v)
}
// SetEstimatedDistanceInMetersNil sets the value for EstimatedDistanceInMeters to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetEstimatedDistanceInMetersNil() {
	o.EstimatedDistanceInMeters.Set(nil)
}

// UnsetEstimatedDistanceInMeters ensures that no value is present for EstimatedDistanceInMeters, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) UnsetEstimatedDistanceInMeters() {
	o.EstimatedDistanceInMeters.Unset()
}

// GetPlannedConnectingTimeInMinutes returns the PlannedConnectingTimeInMinutes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetPlannedConnectingTimeInMinutes() int32 {
	if o == nil || IsNil(o.PlannedConnectingTimeInMinutes.Get()) {
		var ret int32
		return ret
	}
	return *o.PlannedConnectingTimeInMinutes.Get()
}

// GetPlannedConnectingTimeInMinutesOk returns a tuple with the PlannedConnectingTimeInMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetPlannedConnectingTimeInMinutesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PlannedConnectingTimeInMinutes.Get(), o.PlannedConnectingTimeInMinutes.IsSet()
}

// HasPlannedConnectingTimeInMinutes returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) HasPlannedConnectingTimeInMinutes() bool {
	if o != nil && o.PlannedConnectingTimeInMinutes.IsSet() {
		return true
	}

	return false
}

// SetPlannedConnectingTimeInMinutes gets a reference to the given NullableInt32 and assigns it to the PlannedConnectingTimeInMinutes field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetPlannedConnectingTimeInMinutes(v int32) {
	o.PlannedConnectingTimeInMinutes.Set(&v)
}
// SetPlannedConnectingTimeInMinutesNil sets the value for PlannedConnectingTimeInMinutes to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetPlannedConnectingTimeInMinutesNil() {
	o.PlannedConnectingTimeInMinutes.Set(nil)
}

// UnsetPlannedConnectingTimeInMinutes ensures that no value is present for PlannedConnectingTimeInMinutes, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) UnsetPlannedConnectingTimeInMinutes() {
	o.PlannedConnectingTimeInMinutes.Unset()
}

// GetEstimatedConnectingTimeInMinutes returns the EstimatedConnectingTimeInMinutes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetEstimatedConnectingTimeInMinutes() int32 {
	if o == nil || IsNil(o.EstimatedConnectingTimeInMinutes.Get()) {
		var ret int32
		return ret
	}
	return *o.EstimatedConnectingTimeInMinutes.Get()
}

// GetEstimatedConnectingTimeInMinutesOk returns a tuple with the EstimatedConnectingTimeInMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetEstimatedConnectingTimeInMinutesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.EstimatedConnectingTimeInMinutes.Get(), o.EstimatedConnectingTimeInMinutes.IsSet()
}

// HasEstimatedConnectingTimeInMinutes returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) HasEstimatedConnectingTimeInMinutes() bool {
	if o != nil && o.EstimatedConnectingTimeInMinutes.IsSet() {
		return true
	}

	return false
}

// SetEstimatedConnectingTimeInMinutes gets a reference to the given NullableInt32 and assigns it to the EstimatedConnectingTimeInMinutes field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetEstimatedConnectingTimeInMinutes(v int32) {
	o.EstimatedConnectingTimeInMinutes.Set(&v)
}
// SetEstimatedConnectingTimeInMinutesNil sets the value for EstimatedConnectingTimeInMinutes to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetEstimatedConnectingTimeInMinutesNil() {
	o.EstimatedConnectingTimeInMinutes.Set(nil)
}

// UnsetEstimatedConnectingTimeInMinutes ensures that no value is present for EstimatedConnectingTimeInMinutes, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) UnsetEstimatedConnectingTimeInMinutes() {
	o.EstimatedConnectingTimeInMinutes.Unset()
}

// GetIsRiskOfMissingConnection returns the IsRiskOfMissingConnection field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetIsRiskOfMissingConnection() bool {
	if o == nil || IsNil(o.IsRiskOfMissingConnection.Get()) {
		var ret bool
		return ret
	}
	return *o.IsRiskOfMissingConnection.Get()
}

// GetIsRiskOfMissingConnectionOk returns a tuple with the IsRiskOfMissingConnection field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetIsRiskOfMissingConnectionOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsRiskOfMissingConnection.Get(), o.IsRiskOfMissingConnection.IsSet()
}

// HasIsRiskOfMissingConnection returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) HasIsRiskOfMissingConnection() bool {
	if o != nil && o.IsRiskOfMissingConnection.IsSet() {
		return true
	}

	return false
}

// SetIsRiskOfMissingConnection gets a reference to the given NullableBool and assigns it to the IsRiskOfMissingConnection field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetIsRiskOfMissingConnection(v bool) {
	o.IsRiskOfMissingConnection.Set(&v)
}
// SetIsRiskOfMissingConnectionNil sets the value for IsRiskOfMissingConnection to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetIsRiskOfMissingConnectionNil() {
	o.IsRiskOfMissingConnection.Set(nil)
}

// UnsetIsRiskOfMissingConnection ensures that no value is present for IsRiskOfMissingConnection, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) UnsetIsRiskOfMissingConnection() {
	o.IsRiskOfMissingConnection.Unset()
}

// GetPlannedDepartureTime returns the PlannedDepartureTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetPlannedDepartureTime() string {
	if o == nil || IsNil(o.PlannedDepartureTime.Get()) {
		var ret string
		return ret
	}
	return *o.PlannedDepartureTime.Get()
}

// GetPlannedDepartureTimeOk returns a tuple with the PlannedDepartureTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetPlannedDepartureTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PlannedDepartureTime.Get(), o.PlannedDepartureTime.IsSet()
}

// HasPlannedDepartureTime returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) HasPlannedDepartureTime() bool {
	if o != nil && o.PlannedDepartureTime.IsSet() {
		return true
	}

	return false
}

// SetPlannedDepartureTime gets a reference to the given NullableString and assigns it to the PlannedDepartureTime field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetPlannedDepartureTime(v string) {
	o.PlannedDepartureTime.Set(&v)
}
// SetPlannedDepartureTimeNil sets the value for PlannedDepartureTime to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetPlannedDepartureTimeNil() {
	o.PlannedDepartureTime.Set(nil)
}

// UnsetPlannedDepartureTime ensures that no value is present for PlannedDepartureTime, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) UnsetPlannedDepartureTime() {
	o.PlannedDepartureTime.Unset()
}

// GetPlannedArrivalTime returns the PlannedArrivalTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetPlannedArrivalTime() string {
	if o == nil || IsNil(o.PlannedArrivalTime.Get()) {
		var ret string
		return ret
	}
	return *o.PlannedArrivalTime.Get()
}

// GetPlannedArrivalTimeOk returns a tuple with the PlannedArrivalTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetPlannedArrivalTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PlannedArrivalTime.Get(), o.PlannedArrivalTime.IsSet()
}

// HasPlannedArrivalTime returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) HasPlannedArrivalTime() bool {
	if o != nil && o.PlannedArrivalTime.IsSet() {
		return true
	}

	return false
}

// SetPlannedArrivalTime gets a reference to the given NullableString and assigns it to the PlannedArrivalTime field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetPlannedArrivalTime(v string) {
	o.PlannedArrivalTime.Set(&v)
}
// SetPlannedArrivalTimeNil sets the value for PlannedArrivalTime to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetPlannedArrivalTimeNil() {
	o.PlannedArrivalTime.Set(nil)
}

// UnsetPlannedArrivalTime ensures that no value is present for PlannedArrivalTime, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) UnsetPlannedArrivalTime() {
	o.PlannedArrivalTime.Unset()
}

// GetPlannedDurationInMinutes returns the PlannedDurationInMinutes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetPlannedDurationInMinutes() int32 {
	if o == nil || IsNil(o.PlannedDurationInMinutes.Get()) {
		var ret int32
		return ret
	}
	return *o.PlannedDurationInMinutes.Get()
}

// GetPlannedDurationInMinutesOk returns a tuple with the PlannedDurationInMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetPlannedDurationInMinutesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PlannedDurationInMinutes.Get(), o.PlannedDurationInMinutes.IsSet()
}

// HasPlannedDurationInMinutes returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) HasPlannedDurationInMinutes() bool {
	if o != nil && o.PlannedDurationInMinutes.IsSet() {
		return true
	}

	return false
}

// SetPlannedDurationInMinutes gets a reference to the given NullableInt32 and assigns it to the PlannedDurationInMinutes field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetPlannedDurationInMinutes(v int32) {
	o.PlannedDurationInMinutes.Set(&v)
}
// SetPlannedDurationInMinutesNil sets the value for PlannedDurationInMinutes to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetPlannedDurationInMinutesNil() {
	o.PlannedDurationInMinutes.Set(nil)
}

// UnsetPlannedDurationInMinutes ensures that no value is present for PlannedDurationInMinutes, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) UnsetPlannedDurationInMinutes() {
	o.PlannedDurationInMinutes.Unset()
}

// GetEstimatedDepartureTime returns the EstimatedDepartureTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetEstimatedDepartureTime() string {
	if o == nil || IsNil(o.EstimatedDepartureTime.Get()) {
		var ret string
		return ret
	}
	return *o.EstimatedDepartureTime.Get()
}

// GetEstimatedDepartureTimeOk returns a tuple with the EstimatedDepartureTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetEstimatedDepartureTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EstimatedDepartureTime.Get(), o.EstimatedDepartureTime.IsSet()
}

// HasEstimatedDepartureTime returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) HasEstimatedDepartureTime() bool {
	if o != nil && o.EstimatedDepartureTime.IsSet() {
		return true
	}

	return false
}

// SetEstimatedDepartureTime gets a reference to the given NullableString and assigns it to the EstimatedDepartureTime field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetEstimatedDepartureTime(v string) {
	o.EstimatedDepartureTime.Set(&v)
}
// SetEstimatedDepartureTimeNil sets the value for EstimatedDepartureTime to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetEstimatedDepartureTimeNil() {
	o.EstimatedDepartureTime.Set(nil)
}

// UnsetEstimatedDepartureTime ensures that no value is present for EstimatedDepartureTime, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) UnsetEstimatedDepartureTime() {
	o.EstimatedDepartureTime.Unset()
}

// GetEstimatedArrivalTime returns the EstimatedArrivalTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetEstimatedArrivalTime() string {
	if o == nil || IsNil(o.EstimatedArrivalTime.Get()) {
		var ret string
		return ret
	}
	return *o.EstimatedArrivalTime.Get()
}

// GetEstimatedArrivalTimeOk returns a tuple with the EstimatedArrivalTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetEstimatedArrivalTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EstimatedArrivalTime.Get(), o.EstimatedArrivalTime.IsSet()
}

// HasEstimatedArrivalTime returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) HasEstimatedArrivalTime() bool {
	if o != nil && o.EstimatedArrivalTime.IsSet() {
		return true
	}

	return false
}

// SetEstimatedArrivalTime gets a reference to the given NullableString and assigns it to the EstimatedArrivalTime field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetEstimatedArrivalTime(v string) {
	o.EstimatedArrivalTime.Set(&v)
}
// SetEstimatedArrivalTimeNil sets the value for EstimatedArrivalTime to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetEstimatedArrivalTimeNil() {
	o.EstimatedArrivalTime.Set(nil)
}

// UnsetEstimatedArrivalTime ensures that no value is present for EstimatedArrivalTime, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) UnsetEstimatedArrivalTime() {
	o.EstimatedArrivalTime.Unset()
}

// GetEstimatedDurationInMinutes returns the EstimatedDurationInMinutes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetEstimatedDurationInMinutes() int32 {
	if o == nil || IsNil(o.EstimatedDurationInMinutes.Get()) {
		var ret int32
		return ret
	}
	return *o.EstimatedDurationInMinutes.Get()
}

// GetEstimatedDurationInMinutesOk returns a tuple with the EstimatedDurationInMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetEstimatedDurationInMinutesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.EstimatedDurationInMinutes.Get(), o.EstimatedDurationInMinutes.IsSet()
}

// HasEstimatedDurationInMinutes returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) HasEstimatedDurationInMinutes() bool {
	if o != nil && o.EstimatedDurationInMinutes.IsSet() {
		return true
	}

	return false
}

// SetEstimatedDurationInMinutes gets a reference to the given NullableInt32 and assigns it to the EstimatedDurationInMinutes field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetEstimatedDurationInMinutes(v int32) {
	o.EstimatedDurationInMinutes.Set(&v)
}
// SetEstimatedDurationInMinutesNil sets the value for EstimatedDurationInMinutes to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetEstimatedDurationInMinutesNil() {
	o.EstimatedDurationInMinutes.Set(nil)
}

// UnsetEstimatedDurationInMinutes ensures that no value is present for EstimatedDurationInMinutes, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) UnsetEstimatedDurationInMinutes() {
	o.EstimatedDurationInMinutes.Unset()
}

// GetEstimatedOtherwisePlannedArrivalTime returns the EstimatedOtherwisePlannedArrivalTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetEstimatedOtherwisePlannedArrivalTime() string {
	if o == nil || IsNil(o.EstimatedOtherwisePlannedArrivalTime.Get()) {
		var ret string
		return ret
	}
	return *o.EstimatedOtherwisePlannedArrivalTime.Get()
}

// GetEstimatedOtherwisePlannedArrivalTimeOk returns a tuple with the EstimatedOtherwisePlannedArrivalTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetEstimatedOtherwisePlannedArrivalTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EstimatedOtherwisePlannedArrivalTime.Get(), o.EstimatedOtherwisePlannedArrivalTime.IsSet()
}

// HasEstimatedOtherwisePlannedArrivalTime returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) HasEstimatedOtherwisePlannedArrivalTime() bool {
	if o != nil && o.EstimatedOtherwisePlannedArrivalTime.IsSet() {
		return true
	}

	return false
}

// SetEstimatedOtherwisePlannedArrivalTime gets a reference to the given NullableString and assigns it to the EstimatedOtherwisePlannedArrivalTime field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetEstimatedOtherwisePlannedArrivalTime(v string) {
	o.EstimatedOtherwisePlannedArrivalTime.Set(&v)
}
// SetEstimatedOtherwisePlannedArrivalTimeNil sets the value for EstimatedOtherwisePlannedArrivalTime to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetEstimatedOtherwisePlannedArrivalTimeNil() {
	o.EstimatedOtherwisePlannedArrivalTime.Set(nil)
}

// UnsetEstimatedOtherwisePlannedArrivalTime ensures that no value is present for EstimatedOtherwisePlannedArrivalTime, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) UnsetEstimatedOtherwisePlannedArrivalTime() {
	o.EstimatedOtherwisePlannedArrivalTime.Unset()
}

// GetEstimatedOtherwisePlannedDepartureTime returns the EstimatedOtherwisePlannedDepartureTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetEstimatedOtherwisePlannedDepartureTime() string {
	if o == nil || IsNil(o.EstimatedOtherwisePlannedDepartureTime.Get()) {
		var ret string
		return ret
	}
	return *o.EstimatedOtherwisePlannedDepartureTime.Get()
}

// GetEstimatedOtherwisePlannedDepartureTimeOk returns a tuple with the EstimatedOtherwisePlannedDepartureTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetEstimatedOtherwisePlannedDepartureTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EstimatedOtherwisePlannedDepartureTime.Get(), o.EstimatedOtherwisePlannedDepartureTime.IsSet()
}

// HasEstimatedOtherwisePlannedDepartureTime returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) HasEstimatedOtherwisePlannedDepartureTime() bool {
	if o != nil && o.EstimatedOtherwisePlannedDepartureTime.IsSet() {
		return true
	}

	return false
}

// SetEstimatedOtherwisePlannedDepartureTime gets a reference to the given NullableString and assigns it to the EstimatedOtherwisePlannedDepartureTime field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetEstimatedOtherwisePlannedDepartureTime(v string) {
	o.EstimatedOtherwisePlannedDepartureTime.Set(&v)
}
// SetEstimatedOtherwisePlannedDepartureTimeNil sets the value for EstimatedOtherwisePlannedDepartureTime to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetEstimatedOtherwisePlannedDepartureTimeNil() {
	o.EstimatedOtherwisePlannedDepartureTime.Set(nil)
}

// UnsetEstimatedOtherwisePlannedDepartureTime ensures that no value is present for EstimatedOtherwisePlannedDepartureTime, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) UnsetEstimatedOtherwisePlannedDepartureTime() {
	o.EstimatedOtherwisePlannedDepartureTime.Unset()
}

// GetOccupancy returns the Occupancy field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetOccupancy() VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel {
	if o == nil || IsNil(o.Occupancy) {
		var ret VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel
		return ret
	}
	return *o.Occupancy
}

// GetOccupancyOk returns a tuple with the Occupancy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetOccupancyOk() (*VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel, bool) {
	if o == nil || IsNil(o.Occupancy) {
		return nil, false
	}
	return o.Occupancy, true
}

// HasOccupancy returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) HasOccupancy() bool {
	if o != nil && !IsNil(o.Occupancy) {
		return true
	}

	return false
}

// SetOccupancy gets a reference to the given VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel and assigns it to the Occupancy field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetOccupancy(v VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel) {
	o.Occupancy = &v
}

// GetJourneyLegIndex returns the JourneyLegIndex field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetJourneyLegIndex() int32 {
	if o == nil || IsNil(o.JourneyLegIndex) {
		var ret int32
		return ret
	}
	return *o.JourneyLegIndex
}

// GetJourneyLegIndexOk returns a tuple with the JourneyLegIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) GetJourneyLegIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.JourneyLegIndex) {
		return nil, false
	}
	return o.JourneyLegIndex, true
}

// HasJourneyLegIndex returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) HasJourneyLegIndex() bool {
	if o != nil && !IsNil(o.JourneyLegIndex) {
		return true
	}

	return false
}

// SetJourneyLegIndex gets a reference to the given int32 and assigns it to the JourneyLegIndex field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) SetJourneyLegIndex(v int32) {
	o.JourneyLegIndex = &v
}

func (o VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["origin"] = o.Origin
	toSerialize["destination"] = o.Destination
	toSerialize["isCancelled"] = o.IsCancelled
	if !IsNil(o.IsPartCancelled) {
		toSerialize["isPartCancelled"] = o.IsPartCancelled
	}
	if !IsNil(o.ServiceJourney) {
		toSerialize["serviceJourney"] = o.ServiceJourney
	}
	if o.Notes != nil {
		toSerialize["notes"] = o.Notes
	}
	if o.EstimatedDistanceInMeters.IsSet() {
		toSerialize["estimatedDistanceInMeters"] = o.EstimatedDistanceInMeters.Get()
	}
	if o.PlannedConnectingTimeInMinutes.IsSet() {
		toSerialize["plannedConnectingTimeInMinutes"] = o.PlannedConnectingTimeInMinutes.Get()
	}
	if o.EstimatedConnectingTimeInMinutes.IsSet() {
		toSerialize["estimatedConnectingTimeInMinutes"] = o.EstimatedConnectingTimeInMinutes.Get()
	}
	if o.IsRiskOfMissingConnection.IsSet() {
		toSerialize["isRiskOfMissingConnection"] = o.IsRiskOfMissingConnection.Get()
	}
	if o.PlannedDepartureTime.IsSet() {
		toSerialize["plannedDepartureTime"] = o.PlannedDepartureTime.Get()
	}
	if o.PlannedArrivalTime.IsSet() {
		toSerialize["plannedArrivalTime"] = o.PlannedArrivalTime.Get()
	}
	if o.PlannedDurationInMinutes.IsSet() {
		toSerialize["plannedDurationInMinutes"] = o.PlannedDurationInMinutes.Get()
	}
	if o.EstimatedDepartureTime.IsSet() {
		toSerialize["estimatedDepartureTime"] = o.EstimatedDepartureTime.Get()
	}
	if o.EstimatedArrivalTime.IsSet() {
		toSerialize["estimatedArrivalTime"] = o.EstimatedArrivalTime.Get()
	}
	if o.EstimatedDurationInMinutes.IsSet() {
		toSerialize["estimatedDurationInMinutes"] = o.EstimatedDurationInMinutes.Get()
	}
	if o.EstimatedOtherwisePlannedArrivalTime.IsSet() {
		toSerialize["estimatedOtherwisePlannedArrivalTime"] = o.EstimatedOtherwisePlannedArrivalTime.Get()
	}
	if o.EstimatedOtherwisePlannedDepartureTime.IsSet() {
		toSerialize["estimatedOtherwisePlannedDepartureTime"] = o.EstimatedOtherwisePlannedDepartureTime.Get()
	}
	if !IsNil(o.Occupancy) {
		toSerialize["occupancy"] = o.Occupancy
	}
	if !IsNil(o.JourneyLegIndex) {
		toSerialize["journeyLegIndex"] = o.JourneyLegIndex
	}
	return toSerialize, nil
}

type NullableVTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel struct {
	value *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel
	isSet bool
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) Get() *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel {
	return v.value
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) Set(val *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel(val *VTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) *NullableVTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel {
	return &NullableVTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel{value: val, isSet: true}
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneysTripLegApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


