/*
Planera Resa

Sök och planera resor med Västtrafik

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel{}

// VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel Contains information about occupancy.
type VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel struct {
	Level *VTApiPlaneraResaWebV4ModelsOccupancyLevel `json:"level,omitempty"`
	Source *VTApiPlaneraResaWebV4ModelsOccupancyInformationSource `json:"source,omitempty"`
}

// NewVTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel instantiates a new VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel() *VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel {
	this := VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel{}
	return &this
}

// NewVTApiPlaneraResaWebV4ModelsOccupancyInformationApiModelWithDefaults instantiates a new VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVTApiPlaneraResaWebV4ModelsOccupancyInformationApiModelWithDefaults() *VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel {
	this := VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel{}
	return &this
}

// GetLevel returns the Level field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel) GetLevel() VTApiPlaneraResaWebV4ModelsOccupancyLevel {
	if o == nil || IsNil(o.Level) {
		var ret VTApiPlaneraResaWebV4ModelsOccupancyLevel
		return ret
	}
	return *o.Level
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel) GetLevelOk() (*VTApiPlaneraResaWebV4ModelsOccupancyLevel, bool) {
	if o == nil || IsNil(o.Level) {
		return nil, false
	}
	return o.Level, true
}

// HasLevel returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel) HasLevel() bool {
	if o != nil && !IsNil(o.Level) {
		return true
	}

	return false
}

// SetLevel gets a reference to the given VTApiPlaneraResaWebV4ModelsOccupancyLevel and assigns it to the Level field.
func (o *VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel) SetLevel(v VTApiPlaneraResaWebV4ModelsOccupancyLevel) {
	o.Level = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel) GetSource() VTApiPlaneraResaWebV4ModelsOccupancyInformationSource {
	if o == nil || IsNil(o.Source) {
		var ret VTApiPlaneraResaWebV4ModelsOccupancyInformationSource
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel) GetSourceOk() (*VTApiPlaneraResaWebV4ModelsOccupancyInformationSource, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given VTApiPlaneraResaWebV4ModelsOccupancyInformationSource and assigns it to the Source field.
func (o *VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel) SetSource(v VTApiPlaneraResaWebV4ModelsOccupancyInformationSource) {
	o.Source = &v
}

func (o VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Level) {
		toSerialize["level"] = o.Level
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	return toSerialize, nil
}

type NullableVTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel struct {
	value *VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel
	isSet bool
}

func (v NullableVTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel) Get() *VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel {
	return v.value
}

func (v *NullableVTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel) Set(val *VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableVTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableVTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel(val *VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel) *NullableVTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel {
	return &NullableVTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel{value: val, isSet: true}
}

func (v NullableVTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


