/*
Planera Resa

Sök och planera resor med Västtrafik

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel{}

// VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel Describes the duration of validity of a single punch.
type VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel struct {
	Unit *VTApiPlaneraResaWebV4ModelsPunchConfigurationDurationUnitApiModel `json:"unit,omitempty"`
	// Duration of validity of a single punch.
	Amount NullableInt32 `json:"amount,omitempty"`
}

// NewVTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel instantiates a new VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel() *VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel {
	this := VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel{}
	return &this
}

// NewVTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModelWithDefaults instantiates a new VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModelWithDefaults() *VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel {
	this := VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel{}
	return &this
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel) GetUnit() VTApiPlaneraResaWebV4ModelsPunchConfigurationDurationUnitApiModel {
	if o == nil || IsNil(o.Unit) {
		var ret VTApiPlaneraResaWebV4ModelsPunchConfigurationDurationUnitApiModel
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel) GetUnitOk() (*VTApiPlaneraResaWebV4ModelsPunchConfigurationDurationUnitApiModel, bool) {
	if o == nil || IsNil(o.Unit) {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel) HasUnit() bool {
	if o != nil && !IsNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given VTApiPlaneraResaWebV4ModelsPunchConfigurationDurationUnitApiModel and assigns it to the Unit field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel) SetUnit(v VTApiPlaneraResaWebV4ModelsPunchConfigurationDurationUnitApiModel) {
	o.Unit = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel) GetAmount() int32 {
	if o == nil || IsNil(o.Amount.Get()) {
		var ret int32
		return ret
	}
	return *o.Amount.Get()
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Amount.Get(), o.Amount.IsSet()
}

// HasAmount returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel) HasAmount() bool {
	if o != nil && o.Amount.IsSet() {
		return true
	}

	return false
}

// SetAmount gets a reference to the given NullableInt32 and assigns it to the Amount field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel) SetAmount(v int32) {
	o.Amount.Set(&v)
}
// SetAmountNil sets the value for Amount to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel) SetAmountNil() {
	o.Amount.Set(nil)
}

// UnsetAmount ensures that no value is present for Amount, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel) UnsetAmount() {
	o.Amount.Unset()
}

func (o VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Unit) {
		toSerialize["unit"] = o.Unit
	}
	if o.Amount.IsSet() {
		toSerialize["amount"] = o.Amount.Get()
	}
	return toSerialize, nil
}

type NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel struct {
	value *VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel
	isSet bool
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel) Get() *VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel {
	return v.value
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel) Set(val *VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel(val *VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel) *NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel {
	return &NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel{value: val, isSet: true}
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


