/*
Planera Resa

Sök och planera resor med Västtrafik

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel{}

// VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel Information about a line.
type VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel struct {
	// The line name.
	Name NullableString `json:"name,omitempty"`
	// The background color of the line symbol.
	BackgroundColor NullableString `json:"backgroundColor,omitempty"`
	// The foreground color of the line symbol.
	ForegroundColor NullableString `json:"foregroundColor,omitempty"`
	// The border color of the line symbol.
	BorderColor NullableString `json:"borderColor,omitempty"`
	TransportMode *VTApiPlaneraResaCoreModelsTransportMode `json:"transportMode,omitempty"`
	TransportSubMode *VTApiPlaneraResaCoreModelsTransportSubMode `json:"transportSubMode,omitempty"`
}

// NewVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel instantiates a new VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel() *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel {
	this := VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel{}
	return &this
}

// NewVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModelWithDefaults instantiates a new VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModelWithDefaults() *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel {
	this := VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) UnsetName() {
	o.Name.Unset()
}

// GetBackgroundColor returns the BackgroundColor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) GetBackgroundColor() string {
	if o == nil || IsNil(o.BackgroundColor.Get()) {
		var ret string
		return ret
	}
	return *o.BackgroundColor.Get()
}

// GetBackgroundColorOk returns a tuple with the BackgroundColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) GetBackgroundColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BackgroundColor.Get(), o.BackgroundColor.IsSet()
}

// HasBackgroundColor returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) HasBackgroundColor() bool {
	if o != nil && o.BackgroundColor.IsSet() {
		return true
	}

	return false
}

// SetBackgroundColor gets a reference to the given NullableString and assigns it to the BackgroundColor field.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) SetBackgroundColor(v string) {
	o.BackgroundColor.Set(&v)
}
// SetBackgroundColorNil sets the value for BackgroundColor to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) SetBackgroundColorNil() {
	o.BackgroundColor.Set(nil)
}

// UnsetBackgroundColor ensures that no value is present for BackgroundColor, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) UnsetBackgroundColor() {
	o.BackgroundColor.Unset()
}

// GetForegroundColor returns the ForegroundColor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) GetForegroundColor() string {
	if o == nil || IsNil(o.ForegroundColor.Get()) {
		var ret string
		return ret
	}
	return *o.ForegroundColor.Get()
}

// GetForegroundColorOk returns a tuple with the ForegroundColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) GetForegroundColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ForegroundColor.Get(), o.ForegroundColor.IsSet()
}

// HasForegroundColor returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) HasForegroundColor() bool {
	if o != nil && o.ForegroundColor.IsSet() {
		return true
	}

	return false
}

// SetForegroundColor gets a reference to the given NullableString and assigns it to the ForegroundColor field.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) SetForegroundColor(v string) {
	o.ForegroundColor.Set(&v)
}
// SetForegroundColorNil sets the value for ForegroundColor to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) SetForegroundColorNil() {
	o.ForegroundColor.Set(nil)
}

// UnsetForegroundColor ensures that no value is present for ForegroundColor, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) UnsetForegroundColor() {
	o.ForegroundColor.Unset()
}

// GetBorderColor returns the BorderColor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) GetBorderColor() string {
	if o == nil || IsNil(o.BorderColor.Get()) {
		var ret string
		return ret
	}
	return *o.BorderColor.Get()
}

// GetBorderColorOk returns a tuple with the BorderColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) GetBorderColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BorderColor.Get(), o.BorderColor.IsSet()
}

// HasBorderColor returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) HasBorderColor() bool {
	if o != nil && o.BorderColor.IsSet() {
		return true
	}

	return false
}

// SetBorderColor gets a reference to the given NullableString and assigns it to the BorderColor field.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) SetBorderColor(v string) {
	o.BorderColor.Set(&v)
}
// SetBorderColorNil sets the value for BorderColor to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) SetBorderColorNil() {
	o.BorderColor.Set(nil)
}

// UnsetBorderColor ensures that no value is present for BorderColor, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) UnsetBorderColor() {
	o.BorderColor.Unset()
}

// GetTransportMode returns the TransportMode field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) GetTransportMode() VTApiPlaneraResaCoreModelsTransportMode {
	if o == nil || IsNil(o.TransportMode) {
		var ret VTApiPlaneraResaCoreModelsTransportMode
		return ret
	}
	return *o.TransportMode
}

// GetTransportModeOk returns a tuple with the TransportMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) GetTransportModeOk() (*VTApiPlaneraResaCoreModelsTransportMode, bool) {
	if o == nil || IsNil(o.TransportMode) {
		return nil, false
	}
	return o.TransportMode, true
}

// HasTransportMode returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) HasTransportMode() bool {
	if o != nil && !IsNil(o.TransportMode) {
		return true
	}

	return false
}

// SetTransportMode gets a reference to the given VTApiPlaneraResaCoreModelsTransportMode and assigns it to the TransportMode field.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) SetTransportMode(v VTApiPlaneraResaCoreModelsTransportMode) {
	o.TransportMode = &v
}

// GetTransportSubMode returns the TransportSubMode field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) GetTransportSubMode() VTApiPlaneraResaCoreModelsTransportSubMode {
	if o == nil || IsNil(o.TransportSubMode) {
		var ret VTApiPlaneraResaCoreModelsTransportSubMode
		return ret
	}
	return *o.TransportSubMode
}

// GetTransportSubModeOk returns a tuple with the TransportSubMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) GetTransportSubModeOk() (*VTApiPlaneraResaCoreModelsTransportSubMode, bool) {
	if o == nil || IsNil(o.TransportSubMode) {
		return nil, false
	}
	return o.TransportSubMode, true
}

// HasTransportSubMode returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) HasTransportSubMode() bool {
	if o != nil && !IsNil(o.TransportSubMode) {
		return true
	}

	return false
}

// SetTransportSubMode gets a reference to the given VTApiPlaneraResaCoreModelsTransportSubMode and assigns it to the TransportSubMode field.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) SetTransportSubMode(v VTApiPlaneraResaCoreModelsTransportSubMode) {
	o.TransportSubMode = &v
}

func (o VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.BackgroundColor.IsSet() {
		toSerialize["backgroundColor"] = o.BackgroundColor.Get()
	}
	if o.ForegroundColor.IsSet() {
		toSerialize["foregroundColor"] = o.ForegroundColor.Get()
	}
	if o.BorderColor.IsSet() {
		toSerialize["borderColor"] = o.BorderColor.Get()
	}
	if !IsNil(o.TransportMode) {
		toSerialize["transportMode"] = o.TransportMode
	}
	if !IsNil(o.TransportSubMode) {
		toSerialize["transportSubMode"] = o.TransportSubMode
	}
	return toSerialize, nil
}

type NullableVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel struct {
	value *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel
	isSet bool
}

func (v NullableVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) Get() *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel {
	return v.value
}

func (v *NullableVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) Set(val *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel(val *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) *NullableVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel {
	return &NullableVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel{value: val, isSet: true}
}

func (v NullableVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


