/*
Planera Resa

Sök och planera resor med Västtrafik

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// VTApiPlaneraResaWebV4ModelsJourneyTransportMode A subset of TransportMode
type VTApiPlaneraResaWebV4ModelsJourneyTransportMode string

// List of VT.ApiPlaneraResa.Web.V4.Models.JourneyTransportMode
const (
	VTAPIPLANERARESAWEBV4MODELSJOURNEYTRANSPORTMODE_TRAM VTApiPlaneraResaWebV4ModelsJourneyTransportMode = "tram"
	VTAPIPLANERARESAWEBV4MODELSJOURNEYTRANSPORTMODE_BUS VTApiPlaneraResaWebV4ModelsJourneyTransportMode = "bus"
	VTAPIPLANERARESAWEBV4MODELSJOURNEYTRANSPORTMODE_FERRY VTApiPlaneraResaWebV4ModelsJourneyTransportMode = "ferry"
	VTAPIPLANERARESAWEBV4MODELSJOURNEYTRANSPORTMODE_TRAIN VTApiPlaneraResaWebV4ModelsJourneyTransportMode = "train"
	VTAPIPLANERARESAWEBV4MODELSJOURNEYTRANSPORTMODE_TAXI VTApiPlaneraResaWebV4ModelsJourneyTransportMode = "taxi"
	VTAPIPLANERARESAWEBV4MODELSJOURNEYTRANSPORTMODE_WALK VTApiPlaneraResaWebV4ModelsJourneyTransportMode = "walk"
	VTAPIPLANERARESAWEBV4MODELSJOURNEYTRANSPORTMODE_BIKE VTApiPlaneraResaWebV4ModelsJourneyTransportMode = "bike"
	VTAPIPLANERARESAWEBV4MODELSJOURNEYTRANSPORTMODE_CAR VTApiPlaneraResaWebV4ModelsJourneyTransportMode = "car"
)

// All allowed values of VTApiPlaneraResaWebV4ModelsJourneyTransportMode enum
var AllowedVTApiPlaneraResaWebV4ModelsJourneyTransportModeEnumValues = []VTApiPlaneraResaWebV4ModelsJourneyTransportMode{
	"tram",
	"bus",
	"ferry",
	"train",
	"taxi",
	"walk",
	"bike",
	"car",
}

func (v *VTApiPlaneraResaWebV4ModelsJourneyTransportMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := VTApiPlaneraResaWebV4ModelsJourneyTransportMode(value)
	for _, existing := range AllowedVTApiPlaneraResaWebV4ModelsJourneyTransportModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid VTApiPlaneraResaWebV4ModelsJourneyTransportMode", value)
}

// NewVTApiPlaneraResaWebV4ModelsJourneyTransportModeFromValue returns a pointer to a valid VTApiPlaneraResaWebV4ModelsJourneyTransportMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewVTApiPlaneraResaWebV4ModelsJourneyTransportModeFromValue(v string) (*VTApiPlaneraResaWebV4ModelsJourneyTransportMode, error) {
	ev := VTApiPlaneraResaWebV4ModelsJourneyTransportMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for VTApiPlaneraResaWebV4ModelsJourneyTransportMode: valid values are %v", v, AllowedVTApiPlaneraResaWebV4ModelsJourneyTransportModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v VTApiPlaneraResaWebV4ModelsJourneyTransportMode) IsValid() bool {
	for _, existing := range AllowedVTApiPlaneraResaWebV4ModelsJourneyTransportModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to VT.ApiPlaneraResa.Web.V4.Models.JourneyTransportMode value
func (v VTApiPlaneraResaWebV4ModelsJourneyTransportMode) Ptr() *VTApiPlaneraResaWebV4ModelsJourneyTransportMode {
	return &v
}

type NullableVTApiPlaneraResaWebV4ModelsJourneyTransportMode struct {
	value *VTApiPlaneraResaWebV4ModelsJourneyTransportMode
	isSet bool
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneyTransportMode) Get() *VTApiPlaneraResaWebV4ModelsJourneyTransportMode {
	return v.value
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneyTransportMode) Set(val *VTApiPlaneraResaWebV4ModelsJourneyTransportMode) {
	v.value = val
	v.isSet = true
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneyTransportMode) IsSet() bool {
	return v.isSet
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneyTransportMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVTApiPlaneraResaWebV4ModelsJourneyTransportMode(val *VTApiPlaneraResaWebV4ModelsJourneyTransportMode) *NullableVTApiPlaneraResaWebV4ModelsJourneyTransportMode {
	return &NullableVTApiPlaneraResaWebV4ModelsJourneyTransportMode{value: val, isSet: true}
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneyTransportMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneyTransportMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

