/*
Planera Resa

Sök och planera resor med Västtrafik

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel{}

// VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel Information about a ticket suggestion.
type VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel struct {
	// The product id.
	ProductId *int32 `json:"productId,omitempty"`
	// The product name.
	ProductName NullableString `json:"productName,omitempty"`
	// The product type.
	ProductType *int32 `json:"productType,omitempty"`
	TravellerCategory *VTApiPlaneraResaCoreModelsTravellerCategory `json:"travellerCategory,omitempty"`
	// The product price in SEK.
	PriceInSek *float64 `json:"priceInSek,omitempty"`
	TimeValidity *VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel `json:"timeValidity,omitempty"`
	TimeLimitation *VTApiPlaneraResaCoreModelsTimeLimitation `json:"timeLimitation,omitempty"`
	// A list of the channels that sell the product.
	SaleChannels []VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel `json:"saleChannels,omitempty"`
	// A list of the valid zones for the ticket.
	ValidZones []VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel `json:"validZones,omitempty"`
	ProductInstanceType *VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModel `json:"productInstanceType,omitempty"`
	PunchConfiguration *VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel `json:"punchConfiguration,omitempty"`
	// Used to get ticket offer.
	OfferSpecification NullableString `json:"offerSpecification,omitempty"`
}

// NewVTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel instantiates a new VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel() *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel {
	this := VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel{}
	return &this
}

// NewVTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModelWithDefaults instantiates a new VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModelWithDefaults() *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel {
	this := VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel{}
	return &this
}

// GetProductId returns the ProductId field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetProductId() int32 {
	if o == nil || IsNil(o.ProductId) {
		var ret int32
		return ret
	}
	return *o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetProductIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProductId) {
		return nil, false
	}
	return o.ProductId, true
}

// HasProductId returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) HasProductId() bool {
	if o != nil && !IsNil(o.ProductId) {
		return true
	}

	return false
}

// SetProductId gets a reference to the given int32 and assigns it to the ProductId field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) SetProductId(v int32) {
	o.ProductId = &v
}

// GetProductName returns the ProductName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetProductName() string {
	if o == nil || IsNil(o.ProductName.Get()) {
		var ret string
		return ret
	}
	return *o.ProductName.Get()
}

// GetProductNameOk returns a tuple with the ProductName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetProductNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProductName.Get(), o.ProductName.IsSet()
}

// HasProductName returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) HasProductName() bool {
	if o != nil && o.ProductName.IsSet() {
		return true
	}

	return false
}

// SetProductName gets a reference to the given NullableString and assigns it to the ProductName field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) SetProductName(v string) {
	o.ProductName.Set(&v)
}
// SetProductNameNil sets the value for ProductName to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) SetProductNameNil() {
	o.ProductName.Set(nil)
}

// UnsetProductName ensures that no value is present for ProductName, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) UnsetProductName() {
	o.ProductName.Unset()
}

// GetProductType returns the ProductType field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetProductType() int32 {
	if o == nil || IsNil(o.ProductType) {
		var ret int32
		return ret
	}
	return *o.ProductType
}

// GetProductTypeOk returns a tuple with the ProductType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetProductTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.ProductType) {
		return nil, false
	}
	return o.ProductType, true
}

// HasProductType returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) HasProductType() bool {
	if o != nil && !IsNil(o.ProductType) {
		return true
	}

	return false
}

// SetProductType gets a reference to the given int32 and assigns it to the ProductType field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) SetProductType(v int32) {
	o.ProductType = &v
}

// GetTravellerCategory returns the TravellerCategory field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetTravellerCategory() VTApiPlaneraResaCoreModelsTravellerCategory {
	if o == nil || IsNil(o.TravellerCategory) {
		var ret VTApiPlaneraResaCoreModelsTravellerCategory
		return ret
	}
	return *o.TravellerCategory
}

// GetTravellerCategoryOk returns a tuple with the TravellerCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetTravellerCategoryOk() (*VTApiPlaneraResaCoreModelsTravellerCategory, bool) {
	if o == nil || IsNil(o.TravellerCategory) {
		return nil, false
	}
	return o.TravellerCategory, true
}

// HasTravellerCategory returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) HasTravellerCategory() bool {
	if o != nil && !IsNil(o.TravellerCategory) {
		return true
	}

	return false
}

// SetTravellerCategory gets a reference to the given VTApiPlaneraResaCoreModelsTravellerCategory and assigns it to the TravellerCategory field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) SetTravellerCategory(v VTApiPlaneraResaCoreModelsTravellerCategory) {
	o.TravellerCategory = &v
}

// GetPriceInSek returns the PriceInSek field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetPriceInSek() float64 {
	if o == nil || IsNil(o.PriceInSek) {
		var ret float64
		return ret
	}
	return *o.PriceInSek
}

// GetPriceInSekOk returns a tuple with the PriceInSek field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetPriceInSekOk() (*float64, bool) {
	if o == nil || IsNil(o.PriceInSek) {
		return nil, false
	}
	return o.PriceInSek, true
}

// HasPriceInSek returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) HasPriceInSek() bool {
	if o != nil && !IsNil(o.PriceInSek) {
		return true
	}

	return false
}

// SetPriceInSek gets a reference to the given float64 and assigns it to the PriceInSek field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) SetPriceInSek(v float64) {
	o.PriceInSek = &v
}

// GetTimeValidity returns the TimeValidity field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetTimeValidity() VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel {
	if o == nil || IsNil(o.TimeValidity) {
		var ret VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel
		return ret
	}
	return *o.TimeValidity
}

// GetTimeValidityOk returns a tuple with the TimeValidity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetTimeValidityOk() (*VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel, bool) {
	if o == nil || IsNil(o.TimeValidity) {
		return nil, false
	}
	return o.TimeValidity, true
}

// HasTimeValidity returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) HasTimeValidity() bool {
	if o != nil && !IsNil(o.TimeValidity) {
		return true
	}

	return false
}

// SetTimeValidity gets a reference to the given VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel and assigns it to the TimeValidity field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) SetTimeValidity(v VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel) {
	o.TimeValidity = &v
}

// GetTimeLimitation returns the TimeLimitation field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetTimeLimitation() VTApiPlaneraResaCoreModelsTimeLimitation {
	if o == nil || IsNil(o.TimeLimitation) {
		var ret VTApiPlaneraResaCoreModelsTimeLimitation
		return ret
	}
	return *o.TimeLimitation
}

// GetTimeLimitationOk returns a tuple with the TimeLimitation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetTimeLimitationOk() (*VTApiPlaneraResaCoreModelsTimeLimitation, bool) {
	if o == nil || IsNil(o.TimeLimitation) {
		return nil, false
	}
	return o.TimeLimitation, true
}

// HasTimeLimitation returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) HasTimeLimitation() bool {
	if o != nil && !IsNil(o.TimeLimitation) {
		return true
	}

	return false
}

// SetTimeLimitation gets a reference to the given VTApiPlaneraResaCoreModelsTimeLimitation and assigns it to the TimeLimitation field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) SetTimeLimitation(v VTApiPlaneraResaCoreModelsTimeLimitation) {
	o.TimeLimitation = &v
}

// GetSaleChannels returns the SaleChannels field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetSaleChannels() []VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel {
	if o == nil {
		var ret []VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel
		return ret
	}
	return o.SaleChannels
}

// GetSaleChannelsOk returns a tuple with the SaleChannels field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetSaleChannelsOk() ([]VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel, bool) {
	if o == nil || IsNil(o.SaleChannels) {
		return nil, false
	}
	return o.SaleChannels, true
}

// HasSaleChannels returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) HasSaleChannels() bool {
	if o != nil && IsNil(o.SaleChannels) {
		return true
	}

	return false
}

// SetSaleChannels gets a reference to the given []VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel and assigns it to the SaleChannels field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) SetSaleChannels(v []VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel) {
	o.SaleChannels = v
}

// GetValidZones returns the ValidZones field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetValidZones() []VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel {
	if o == nil {
		var ret []VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel
		return ret
	}
	return o.ValidZones
}

// GetValidZonesOk returns a tuple with the ValidZones field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetValidZonesOk() ([]VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel, bool) {
	if o == nil || IsNil(o.ValidZones) {
		return nil, false
	}
	return o.ValidZones, true
}

// HasValidZones returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) HasValidZones() bool {
	if o != nil && IsNil(o.ValidZones) {
		return true
	}

	return false
}

// SetValidZones gets a reference to the given []VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel and assigns it to the ValidZones field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) SetValidZones(v []VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel) {
	o.ValidZones = v
}

// GetProductInstanceType returns the ProductInstanceType field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetProductInstanceType() VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModel {
	if o == nil || IsNil(o.ProductInstanceType) {
		var ret VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModel
		return ret
	}
	return *o.ProductInstanceType
}

// GetProductInstanceTypeOk returns a tuple with the ProductInstanceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetProductInstanceTypeOk() (*VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModel, bool) {
	if o == nil || IsNil(o.ProductInstanceType) {
		return nil, false
	}
	return o.ProductInstanceType, true
}

// HasProductInstanceType returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) HasProductInstanceType() bool {
	if o != nil && !IsNil(o.ProductInstanceType) {
		return true
	}

	return false
}

// SetProductInstanceType gets a reference to the given VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModel and assigns it to the ProductInstanceType field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) SetProductInstanceType(v VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModel) {
	o.ProductInstanceType = &v
}

// GetPunchConfiguration returns the PunchConfiguration field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetPunchConfiguration() VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel {
	if o == nil || IsNil(o.PunchConfiguration) {
		var ret VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel
		return ret
	}
	return *o.PunchConfiguration
}

// GetPunchConfigurationOk returns a tuple with the PunchConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetPunchConfigurationOk() (*VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel, bool) {
	if o == nil || IsNil(o.PunchConfiguration) {
		return nil, false
	}
	return o.PunchConfiguration, true
}

// HasPunchConfiguration returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) HasPunchConfiguration() bool {
	if o != nil && !IsNil(o.PunchConfiguration) {
		return true
	}

	return false
}

// SetPunchConfiguration gets a reference to the given VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel and assigns it to the PunchConfiguration field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) SetPunchConfiguration(v VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel) {
	o.PunchConfiguration = &v
}

// GetOfferSpecification returns the OfferSpecification field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetOfferSpecification() string {
	if o == nil || IsNil(o.OfferSpecification.Get()) {
		var ret string
		return ret
	}
	return *o.OfferSpecification.Get()
}

// GetOfferSpecificationOk returns a tuple with the OfferSpecification field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) GetOfferSpecificationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OfferSpecification.Get(), o.OfferSpecification.IsSet()
}

// HasOfferSpecification returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) HasOfferSpecification() bool {
	if o != nil && o.OfferSpecification.IsSet() {
		return true
	}

	return false
}

// SetOfferSpecification gets a reference to the given NullableString and assigns it to the OfferSpecification field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) SetOfferSpecification(v string) {
	o.OfferSpecification.Set(&v)
}
// SetOfferSpecificationNil sets the value for OfferSpecification to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) SetOfferSpecificationNil() {
	o.OfferSpecification.Set(nil)
}

// UnsetOfferSpecification ensures that no value is present for OfferSpecification, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) UnsetOfferSpecification() {
	o.OfferSpecification.Unset()
}

func (o VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProductId) {
		toSerialize["productId"] = o.ProductId
	}
	if o.ProductName.IsSet() {
		toSerialize["productName"] = o.ProductName.Get()
	}
	if !IsNil(o.ProductType) {
		toSerialize["productType"] = o.ProductType
	}
	if !IsNil(o.TravellerCategory) {
		toSerialize["travellerCategory"] = o.TravellerCategory
	}
	if !IsNil(o.PriceInSek) {
		toSerialize["priceInSek"] = o.PriceInSek
	}
	if !IsNil(o.TimeValidity) {
		toSerialize["timeValidity"] = o.TimeValidity
	}
	if !IsNil(o.TimeLimitation) {
		toSerialize["timeLimitation"] = o.TimeLimitation
	}
	if o.SaleChannels != nil {
		toSerialize["saleChannels"] = o.SaleChannels
	}
	if o.ValidZones != nil {
		toSerialize["validZones"] = o.ValidZones
	}
	if !IsNil(o.ProductInstanceType) {
		toSerialize["productInstanceType"] = o.ProductInstanceType
	}
	if !IsNil(o.PunchConfiguration) {
		toSerialize["punchConfiguration"] = o.PunchConfiguration
	}
	if o.OfferSpecification.IsSet() {
		toSerialize["offerSpecification"] = o.OfferSpecification.Get()
	}
	return toSerialize, nil
}

type NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel struct {
	value *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel
	isSet bool
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) Get() *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel {
	return v.value
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) Set(val *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel(val *VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) *NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel {
	return &NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel{value: val, isSet: true}
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


