/*
Planera Resa

Sök och planera resor med Västtrafik

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VTApiPlaneraResaWebV4ModelsPaginationProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VTApiPlaneraResaWebV4ModelsPaginationProperties{}

// VTApiPlaneraResaWebV4ModelsPaginationProperties Pagination information.
type VTApiPlaneraResaWebV4ModelsPaginationProperties struct {
	// The requested number of results.
	Limit *int32 `json:"limit,omitempty"`
	// The requested offset in the results array.
	Offset *int32 `json:"offset,omitempty"`
	// The actual number of returned results.
	Size *int32 `json:"size,omitempty"`
}

// NewVTApiPlaneraResaWebV4ModelsPaginationProperties instantiates a new VTApiPlaneraResaWebV4ModelsPaginationProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVTApiPlaneraResaWebV4ModelsPaginationProperties() *VTApiPlaneraResaWebV4ModelsPaginationProperties {
	this := VTApiPlaneraResaWebV4ModelsPaginationProperties{}
	return &this
}

// NewVTApiPlaneraResaWebV4ModelsPaginationPropertiesWithDefaults instantiates a new VTApiPlaneraResaWebV4ModelsPaginationProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVTApiPlaneraResaWebV4ModelsPaginationPropertiesWithDefaults() *VTApiPlaneraResaWebV4ModelsPaginationProperties {
	this := VTApiPlaneraResaWebV4ModelsPaginationProperties{}
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsPaginationProperties) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsPaginationProperties) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsPaginationProperties) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *VTApiPlaneraResaWebV4ModelsPaginationProperties) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsPaginationProperties) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsPaginationProperties) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsPaginationProperties) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *VTApiPlaneraResaWebV4ModelsPaginationProperties) SetOffset(v int32) {
	o.Offset = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsPaginationProperties) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsPaginationProperties) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsPaginationProperties) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *VTApiPlaneraResaWebV4ModelsPaginationProperties) SetSize(v int32) {
	o.Size = &v
}

func (o VTApiPlaneraResaWebV4ModelsPaginationProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VTApiPlaneraResaWebV4ModelsPaginationProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	return toSerialize, nil
}

type NullableVTApiPlaneraResaWebV4ModelsPaginationProperties struct {
	value *VTApiPlaneraResaWebV4ModelsPaginationProperties
	isSet bool
}

func (v NullableVTApiPlaneraResaWebV4ModelsPaginationProperties) Get() *VTApiPlaneraResaWebV4ModelsPaginationProperties {
	return v.value
}

func (v *NullableVTApiPlaneraResaWebV4ModelsPaginationProperties) Set(val *VTApiPlaneraResaWebV4ModelsPaginationProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableVTApiPlaneraResaWebV4ModelsPaginationProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableVTApiPlaneraResaWebV4ModelsPaginationProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVTApiPlaneraResaWebV4ModelsPaginationProperties(val *VTApiPlaneraResaWebV4ModelsPaginationProperties) *NullableVTApiPlaneraResaWebV4ModelsPaginationProperties {
	return &NullableVTApiPlaneraResaWebV4ModelsPaginationProperties{value: val, isSet: true}
}

func (v NullableVTApiPlaneraResaWebV4ModelsPaginationProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVTApiPlaneraResaWebV4ModelsPaginationProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


