/*
Planera Resa

Sök och planera resor med Västtrafik

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VTApiPlaneraResaWebV4ModelsJourneysCallApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VTApiPlaneraResaWebV4ModelsJourneysCallApiModel{}

// VTApiPlaneraResaWebV4ModelsJourneysCallApiModel Information about a call on the trip leg.
type VTApiPlaneraResaWebV4ModelsJourneysCallApiModel struct {
	StopPoint VTApiPlaneraResaWebV4ModelsJourneysStopPointApiModel `json:"stopPoint"`
	// The planned time of the call in RFC 3339 format.
	PlannedTime string `json:"plannedTime"`
	// The estimated time of the call in RFC 3339 format.
	EstimatedTime NullableString `json:"estimatedTime,omitempty"`
	// The best known time of the call in RFC 3339 format. Is EstimatedTime if exists, otherwise PlannedTime.
	EstimatedOtherwisePlannedTime NullableString `json:"estimatedOtherwisePlannedTime,omitempty"`
	// An ordered list (most important first) of notes related to the call.
	Notes []VTApiPlaneraResaCoreModelsNote `json:"notes,omitempty"`
}

// NewVTApiPlaneraResaWebV4ModelsJourneysCallApiModel instantiates a new VTApiPlaneraResaWebV4ModelsJourneysCallApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVTApiPlaneraResaWebV4ModelsJourneysCallApiModel(stopPoint VTApiPlaneraResaWebV4ModelsJourneysStopPointApiModel, plannedTime string) *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel {
	this := VTApiPlaneraResaWebV4ModelsJourneysCallApiModel{}
	this.StopPoint = stopPoint
	this.PlannedTime = plannedTime
	return &this
}

// NewVTApiPlaneraResaWebV4ModelsJourneysCallApiModelWithDefaults instantiates a new VTApiPlaneraResaWebV4ModelsJourneysCallApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVTApiPlaneraResaWebV4ModelsJourneysCallApiModelWithDefaults() *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel {
	this := VTApiPlaneraResaWebV4ModelsJourneysCallApiModel{}
	return &this
}

// GetStopPoint returns the StopPoint field value
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) GetStopPoint() VTApiPlaneraResaWebV4ModelsJourneysStopPointApiModel {
	if o == nil {
		var ret VTApiPlaneraResaWebV4ModelsJourneysStopPointApiModel
		return ret
	}

	return o.StopPoint
}

// GetStopPointOk returns a tuple with the StopPoint field value
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) GetStopPointOk() (*VTApiPlaneraResaWebV4ModelsJourneysStopPointApiModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StopPoint, true
}

// SetStopPoint sets field value
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) SetStopPoint(v VTApiPlaneraResaWebV4ModelsJourneysStopPointApiModel) {
	o.StopPoint = v
}

// GetPlannedTime returns the PlannedTime field value
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) GetPlannedTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlannedTime
}

// GetPlannedTimeOk returns a tuple with the PlannedTime field value
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) GetPlannedTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlannedTime, true
}

// SetPlannedTime sets field value
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) SetPlannedTime(v string) {
	o.PlannedTime = v
}

// GetEstimatedTime returns the EstimatedTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) GetEstimatedTime() string {
	if o == nil || IsNil(o.EstimatedTime.Get()) {
		var ret string
		return ret
	}
	return *o.EstimatedTime.Get()
}

// GetEstimatedTimeOk returns a tuple with the EstimatedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) GetEstimatedTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EstimatedTime.Get(), o.EstimatedTime.IsSet()
}

// HasEstimatedTime returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) HasEstimatedTime() bool {
	if o != nil && o.EstimatedTime.IsSet() {
		return true
	}

	return false
}

// SetEstimatedTime gets a reference to the given NullableString and assigns it to the EstimatedTime field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) SetEstimatedTime(v string) {
	o.EstimatedTime.Set(&v)
}
// SetEstimatedTimeNil sets the value for EstimatedTime to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) SetEstimatedTimeNil() {
	o.EstimatedTime.Set(nil)
}

// UnsetEstimatedTime ensures that no value is present for EstimatedTime, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) UnsetEstimatedTime() {
	o.EstimatedTime.Unset()
}

// GetEstimatedOtherwisePlannedTime returns the EstimatedOtherwisePlannedTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) GetEstimatedOtherwisePlannedTime() string {
	if o == nil || IsNil(o.EstimatedOtherwisePlannedTime.Get()) {
		var ret string
		return ret
	}
	return *o.EstimatedOtherwisePlannedTime.Get()
}

// GetEstimatedOtherwisePlannedTimeOk returns a tuple with the EstimatedOtherwisePlannedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) GetEstimatedOtherwisePlannedTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EstimatedOtherwisePlannedTime.Get(), o.EstimatedOtherwisePlannedTime.IsSet()
}

// HasEstimatedOtherwisePlannedTime returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) HasEstimatedOtherwisePlannedTime() bool {
	if o != nil && o.EstimatedOtherwisePlannedTime.IsSet() {
		return true
	}

	return false
}

// SetEstimatedOtherwisePlannedTime gets a reference to the given NullableString and assigns it to the EstimatedOtherwisePlannedTime field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) SetEstimatedOtherwisePlannedTime(v string) {
	o.EstimatedOtherwisePlannedTime.Set(&v)
}
// SetEstimatedOtherwisePlannedTimeNil sets the value for EstimatedOtherwisePlannedTime to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) SetEstimatedOtherwisePlannedTimeNil() {
	o.EstimatedOtherwisePlannedTime.Set(nil)
}

// UnsetEstimatedOtherwisePlannedTime ensures that no value is present for EstimatedOtherwisePlannedTime, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) UnsetEstimatedOtherwisePlannedTime() {
	o.EstimatedOtherwisePlannedTime.Unset()
}

// GetNotes returns the Notes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) GetNotes() []VTApiPlaneraResaCoreModelsNote {
	if o == nil {
		var ret []VTApiPlaneraResaCoreModelsNote
		return ret
	}
	return o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) GetNotesOk() ([]VTApiPlaneraResaCoreModelsNote, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) HasNotes() bool {
	if o != nil && IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given []VTApiPlaneraResaCoreModelsNote and assigns it to the Notes field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) SetNotes(v []VTApiPlaneraResaCoreModelsNote) {
	o.Notes = v
}

func (o VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["stopPoint"] = o.StopPoint
	toSerialize["plannedTime"] = o.PlannedTime
	if o.EstimatedTime.IsSet() {
		toSerialize["estimatedTime"] = o.EstimatedTime.Get()
	}
	if o.EstimatedOtherwisePlannedTime.IsSet() {
		toSerialize["estimatedOtherwisePlannedTime"] = o.EstimatedOtherwisePlannedTime.Get()
	}
	if o.Notes != nil {
		toSerialize["notes"] = o.Notes
	}
	return toSerialize, nil
}

type NullableVTApiPlaneraResaWebV4ModelsJourneysCallApiModel struct {
	value *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel
	isSet bool
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneysCallApiModel) Get() *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel {
	return v.value
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneysCallApiModel) Set(val *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneysCallApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneysCallApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVTApiPlaneraResaWebV4ModelsJourneysCallApiModel(val *VTApiPlaneraResaWebV4ModelsJourneysCallApiModel) *NullableVTApiPlaneraResaWebV4ModelsJourneysCallApiModel {
	return &NullableVTApiPlaneraResaWebV4ModelsJourneysCallApiModel{value: val, isSet: true}
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneysCallApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneysCallApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


