/*
Planera Resa

Sök och planera resor med Västtrafik

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel{}

// VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel Information about a zone related to the ticket suggestion.
type VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel struct {
	// The zone id.
	Id *int32 `json:"id,omitempty"`
}

// NewVTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel instantiates a new VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel() *VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel {
	this := VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel{}
	return &this
}

// NewVTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModelWithDefaults instantiates a new VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModelWithDefaults() *VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel {
	this := VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel) SetId(v int32) {
	o.Id = &v
}

func (o VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel struct {
	value *VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel
	isSet bool
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel) Get() *VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel {
	return v.value
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel) Set(val *VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel(val *VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel) *NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel {
	return &NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel{value: val, isSet: true}
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


