/*
Planera Resa

Sök och planera resor med Västtrafik

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VTApiPlaneraResaWebV4ModelsPaginationLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VTApiPlaneraResaWebV4ModelsPaginationLinks{}

// VTApiPlaneraResaWebV4ModelsPaginationLinks Pagination navigation links.
type VTApiPlaneraResaWebV4ModelsPaginationLinks struct {
	// Link to the previous results page, if available, otherwise null.
	Previous NullableString `json:"previous,omitempty"`
	// Link to the next results page, if available, otherwise null. Not guaranteed to give a result if called.
	Next NullableString `json:"next,omitempty"`
	// Link to the current results page, if available, otherwise null. Not guaranteed to give a result if called.
	Current NullableString `json:"current,omitempty"`
}

// NewVTApiPlaneraResaWebV4ModelsPaginationLinks instantiates a new VTApiPlaneraResaWebV4ModelsPaginationLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVTApiPlaneraResaWebV4ModelsPaginationLinks() *VTApiPlaneraResaWebV4ModelsPaginationLinks {
	this := VTApiPlaneraResaWebV4ModelsPaginationLinks{}
	return &this
}

// NewVTApiPlaneraResaWebV4ModelsPaginationLinksWithDefaults instantiates a new VTApiPlaneraResaWebV4ModelsPaginationLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVTApiPlaneraResaWebV4ModelsPaginationLinksWithDefaults() *VTApiPlaneraResaWebV4ModelsPaginationLinks {
	this := VTApiPlaneraResaWebV4ModelsPaginationLinks{}
	return &this
}

// GetPrevious returns the Previous field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsPaginationLinks) GetPrevious() string {
	if o == nil || IsNil(o.Previous.Get()) {
		var ret string
		return ret
	}
	return *o.Previous.Get()
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsPaginationLinks) GetPreviousOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Previous.Get(), o.Previous.IsSet()
}

// HasPrevious returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsPaginationLinks) HasPrevious() bool {
	if o != nil && o.Previous.IsSet() {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given NullableString and assigns it to the Previous field.
func (o *VTApiPlaneraResaWebV4ModelsPaginationLinks) SetPrevious(v string) {
	o.Previous.Set(&v)
}
// SetPreviousNil sets the value for Previous to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsPaginationLinks) SetPreviousNil() {
	o.Previous.Set(nil)
}

// UnsetPrevious ensures that no value is present for Previous, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsPaginationLinks) UnsetPrevious() {
	o.Previous.Unset()
}

// GetNext returns the Next field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsPaginationLinks) GetNext() string {
	if o == nil || IsNil(o.Next.Get()) {
		var ret string
		return ret
	}
	return *o.Next.Get()
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsPaginationLinks) GetNextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Next.Get(), o.Next.IsSet()
}

// HasNext returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsPaginationLinks) HasNext() bool {
	if o != nil && o.Next.IsSet() {
		return true
	}

	return false
}

// SetNext gets a reference to the given NullableString and assigns it to the Next field.
func (o *VTApiPlaneraResaWebV4ModelsPaginationLinks) SetNext(v string) {
	o.Next.Set(&v)
}
// SetNextNil sets the value for Next to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsPaginationLinks) SetNextNil() {
	o.Next.Set(nil)
}

// UnsetNext ensures that no value is present for Next, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsPaginationLinks) UnsetNext() {
	o.Next.Unset()
}

// GetCurrent returns the Current field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsPaginationLinks) GetCurrent() string {
	if o == nil || IsNil(o.Current.Get()) {
		var ret string
		return ret
	}
	return *o.Current.Get()
}

// GetCurrentOk returns a tuple with the Current field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsPaginationLinks) GetCurrentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Current.Get(), o.Current.IsSet()
}

// HasCurrent returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsPaginationLinks) HasCurrent() bool {
	if o != nil && o.Current.IsSet() {
		return true
	}

	return false
}

// SetCurrent gets a reference to the given NullableString and assigns it to the Current field.
func (o *VTApiPlaneraResaWebV4ModelsPaginationLinks) SetCurrent(v string) {
	o.Current.Set(&v)
}
// SetCurrentNil sets the value for Current to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsPaginationLinks) SetCurrentNil() {
	o.Current.Set(nil)
}

// UnsetCurrent ensures that no value is present for Current, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsPaginationLinks) UnsetCurrent() {
	o.Current.Unset()
}

func (o VTApiPlaneraResaWebV4ModelsPaginationLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VTApiPlaneraResaWebV4ModelsPaginationLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Previous.IsSet() {
		toSerialize["previous"] = o.Previous.Get()
	}
	if o.Next.IsSet() {
		toSerialize["next"] = o.Next.Get()
	}
	if o.Current.IsSet() {
		toSerialize["current"] = o.Current.Get()
	}
	return toSerialize, nil
}

type NullableVTApiPlaneraResaWebV4ModelsPaginationLinks struct {
	value *VTApiPlaneraResaWebV4ModelsPaginationLinks
	isSet bool
}

func (v NullableVTApiPlaneraResaWebV4ModelsPaginationLinks) Get() *VTApiPlaneraResaWebV4ModelsPaginationLinks {
	return v.value
}

func (v *NullableVTApiPlaneraResaWebV4ModelsPaginationLinks) Set(val *VTApiPlaneraResaWebV4ModelsPaginationLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableVTApiPlaneraResaWebV4ModelsPaginationLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableVTApiPlaneraResaWebV4ModelsPaginationLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVTApiPlaneraResaWebV4ModelsPaginationLinks(val *VTApiPlaneraResaWebV4ModelsPaginationLinks) *NullableVTApiPlaneraResaWebV4ModelsPaginationLinks {
	return &NullableVTApiPlaneraResaWebV4ModelsPaginationLinks{value: val, isSet: true}
}

func (v NullableVTApiPlaneraResaWebV4ModelsPaginationLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVTApiPlaneraResaWebV4ModelsPaginationLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


