/*
Planera Resa

Sök och planera resor med Västtrafik

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel{}

// VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel Information about a service journey.
type VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel struct {
	// 16-digit Västtrafik service journey gid.
	Gid NullableString `json:"gid,omitempty"`
	// A description of the direction.
	Direction NullableString `json:"direction,omitempty"`
	Line *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel `json:"line,omitempty"`
	// The coordinates of the service journey.
	ServiceJourneyCoordinates []VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel `json:"serviceJourneyCoordinates,omitempty"`
	// All calls on the service journey.
	CallsOnServiceJourney []VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCallDetailsApiModel `json:"callsOnServiceJourney,omitempty"`
}

// NewVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel instantiates a new VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel() *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel {
	this := VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel{}
	return &this
}

// NewVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModelWithDefaults instantiates a new VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModelWithDefaults() *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel {
	this := VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel{}
	return &this
}

// GetGid returns the Gid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) GetGid() string {
	if o == nil || IsNil(o.Gid.Get()) {
		var ret string
		return ret
	}
	return *o.Gid.Get()
}

// GetGidOk returns a tuple with the Gid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) GetGidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Gid.Get(), o.Gid.IsSet()
}

// HasGid returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) HasGid() bool {
	if o != nil && o.Gid.IsSet() {
		return true
	}

	return false
}

// SetGid gets a reference to the given NullableString and assigns it to the Gid field.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) SetGid(v string) {
	o.Gid.Set(&v)
}
// SetGidNil sets the value for Gid to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) SetGidNil() {
	o.Gid.Set(nil)
}

// UnsetGid ensures that no value is present for Gid, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) UnsetGid() {
	o.Gid.Unset()
}

// GetDirection returns the Direction field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) GetDirection() string {
	if o == nil || IsNil(o.Direction.Get()) {
		var ret string
		return ret
	}
	return *o.Direction.Get()
}

// GetDirectionOk returns a tuple with the Direction field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) GetDirectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Direction.Get(), o.Direction.IsSet()
}

// HasDirection returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) HasDirection() bool {
	if o != nil && o.Direction.IsSet() {
		return true
	}

	return false
}

// SetDirection gets a reference to the given NullableString and assigns it to the Direction field.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) SetDirection(v string) {
	o.Direction.Set(&v)
}
// SetDirectionNil sets the value for Direction to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) SetDirectionNil() {
	o.Direction.Set(nil)
}

// UnsetDirection ensures that no value is present for Direction, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) UnsetDirection() {
	o.Direction.Unset()
}

// GetLine returns the Line field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) GetLine() VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel {
	if o == nil || IsNil(o.Line) {
		var ret VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel
		return ret
	}
	return *o.Line
}

// GetLineOk returns a tuple with the Line field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) GetLineOk() (*VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel, bool) {
	if o == nil || IsNil(o.Line) {
		return nil, false
	}
	return o.Line, true
}

// HasLine returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) HasLine() bool {
	if o != nil && !IsNil(o.Line) {
		return true
	}

	return false
}

// SetLine gets a reference to the given VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel and assigns it to the Line field.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) SetLine(v VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel) {
	o.Line = &v
}

// GetServiceJourneyCoordinates returns the ServiceJourneyCoordinates field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) GetServiceJourneyCoordinates() []VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel {
	if o == nil {
		var ret []VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel
		return ret
	}
	return o.ServiceJourneyCoordinates
}

// GetServiceJourneyCoordinatesOk returns a tuple with the ServiceJourneyCoordinates field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) GetServiceJourneyCoordinatesOk() ([]VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel, bool) {
	if o == nil || IsNil(o.ServiceJourneyCoordinates) {
		return nil, false
	}
	return o.ServiceJourneyCoordinates, true
}

// HasServiceJourneyCoordinates returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) HasServiceJourneyCoordinates() bool {
	if o != nil && IsNil(o.ServiceJourneyCoordinates) {
		return true
	}

	return false
}

// SetServiceJourneyCoordinates gets a reference to the given []VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel and assigns it to the ServiceJourneyCoordinates field.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) SetServiceJourneyCoordinates(v []VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel) {
	o.ServiceJourneyCoordinates = v
}

// GetCallsOnServiceJourney returns the CallsOnServiceJourney field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) GetCallsOnServiceJourney() []VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCallDetailsApiModel {
	if o == nil {
		var ret []VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCallDetailsApiModel
		return ret
	}
	return o.CallsOnServiceJourney
}

// GetCallsOnServiceJourneyOk returns a tuple with the CallsOnServiceJourney field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) GetCallsOnServiceJourneyOk() ([]VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCallDetailsApiModel, bool) {
	if o == nil || IsNil(o.CallsOnServiceJourney) {
		return nil, false
	}
	return o.CallsOnServiceJourney, true
}

// HasCallsOnServiceJourney returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) HasCallsOnServiceJourney() bool {
	if o != nil && IsNil(o.CallsOnServiceJourney) {
		return true
	}

	return false
}

// SetCallsOnServiceJourney gets a reference to the given []VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCallDetailsApiModel and assigns it to the CallsOnServiceJourney field.
func (o *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) SetCallsOnServiceJourney(v []VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCallDetailsApiModel) {
	o.CallsOnServiceJourney = v
}

func (o VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Gid.IsSet() {
		toSerialize["gid"] = o.Gid.Get()
	}
	if o.Direction.IsSet() {
		toSerialize["direction"] = o.Direction.Get()
	}
	if !IsNil(o.Line) {
		toSerialize["line"] = o.Line
	}
	if o.ServiceJourneyCoordinates != nil {
		toSerialize["serviceJourneyCoordinates"] = o.ServiceJourneyCoordinates
	}
	if o.CallsOnServiceJourney != nil {
		toSerialize["callsOnServiceJourney"] = o.CallsOnServiceJourney
	}
	return toSerialize, nil
}

type NullableVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel struct {
	value *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel
	isSet bool
}

func (v NullableVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) Get() *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel {
	return v.value
}

func (v *NullableVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) Set(val *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel(val *VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) *NullableVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel {
	return &NullableVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel{value: val, isSet: true}
}

func (v NullableVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


