/*
Planera Resa

Sök och planera resor med Västtrafik

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel{}

// VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel Information about a service journey of a departure or arrival.
type VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel struct {
	// 16-digit Västtrafik service journey gid.
	Gid string `json:"gid"`
	// A description of the direction.
	Direction NullableString `json:"direction,omitempty"`
	// Västtrafik service journey number that the trip leg is a part of.
	Number NullableString `json:"number,omitempty"`
	Line *VTApiPlaneraResaWebV4ModelsJourneysLineApiModel `json:"line,omitempty"`
}

// NewVTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel instantiates a new VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel(gid string) *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel {
	this := VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel{}
	this.Gid = gid
	return &this
}

// NewVTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModelWithDefaults instantiates a new VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModelWithDefaults() *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel {
	this := VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel{}
	return &this
}

// GetGid returns the Gid field value
func (o *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) GetGid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Gid
}

// GetGidOk returns a tuple with the Gid field value
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) GetGidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gid, true
}

// SetGid sets field value
func (o *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) SetGid(v string) {
	o.Gid = v
}

// GetDirection returns the Direction field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) GetDirection() string {
	if o == nil || IsNil(o.Direction.Get()) {
		var ret string
		return ret
	}
	return *o.Direction.Get()
}

// GetDirectionOk returns a tuple with the Direction field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) GetDirectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Direction.Get(), o.Direction.IsSet()
}

// HasDirection returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) HasDirection() bool {
	if o != nil && o.Direction.IsSet() {
		return true
	}

	return false
}

// SetDirection gets a reference to the given NullableString and assigns it to the Direction field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) SetDirection(v string) {
	o.Direction.Set(&v)
}
// SetDirectionNil sets the value for Direction to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) SetDirectionNil() {
	o.Direction.Set(nil)
}

// UnsetDirection ensures that no value is present for Direction, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) UnsetDirection() {
	o.Direction.Unset()
}

// GetNumber returns the Number field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) GetNumber() string {
	if o == nil || IsNil(o.Number.Get()) {
		var ret string
		return ret
	}
	return *o.Number.Get()
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) GetNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Number.Get(), o.Number.IsSet()
}

// HasNumber returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) HasNumber() bool {
	if o != nil && o.Number.IsSet() {
		return true
	}

	return false
}

// SetNumber gets a reference to the given NullableString and assigns it to the Number field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) SetNumber(v string) {
	o.Number.Set(&v)
}
// SetNumberNil sets the value for Number to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) SetNumberNil() {
	o.Number.Set(nil)
}

// UnsetNumber ensures that no value is present for Number, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) UnsetNumber() {
	o.Number.Unset()
}

// GetLine returns the Line field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) GetLine() VTApiPlaneraResaWebV4ModelsJourneysLineApiModel {
	if o == nil || IsNil(o.Line) {
		var ret VTApiPlaneraResaWebV4ModelsJourneysLineApiModel
		return ret
	}
	return *o.Line
}

// GetLineOk returns a tuple with the Line field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) GetLineOk() (*VTApiPlaneraResaWebV4ModelsJourneysLineApiModel, bool) {
	if o == nil || IsNil(o.Line) {
		return nil, false
	}
	return o.Line, true
}

// HasLine returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) HasLine() bool {
	if o != nil && !IsNil(o.Line) {
		return true
	}

	return false
}

// SetLine gets a reference to the given VTApiPlaneraResaWebV4ModelsJourneysLineApiModel and assigns it to the Line field.
func (o *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) SetLine(v VTApiPlaneraResaWebV4ModelsJourneysLineApiModel) {
	o.Line = &v
}

func (o VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["gid"] = o.Gid
	if o.Direction.IsSet() {
		toSerialize["direction"] = o.Direction.Get()
	}
	if o.Number.IsSet() {
		toSerialize["number"] = o.Number.Get()
	}
	if !IsNil(o.Line) {
		toSerialize["line"] = o.Line
	}
	return toSerialize, nil
}

type NullableVTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel struct {
	value *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel
	isSet bool
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) Get() *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel {
	return v.value
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) Set(val *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel(val *VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) *NullableVTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel {
	return &NullableVTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel{value: val, isSet: true}
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


