/*
Planera Resa

Sök och planera resor med Västtrafik

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel{}

// VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel struct for VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel
type VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel struct {
	// The 16-digit Västtrafik gid of the stop area.
	Gid NullableString `json:"gid,omitempty"`
	// The stop area name.
	Name NullableString `json:"name,omitempty"`
	// The latitude of the stop point.
	Latitude *float64 `json:"latitude,omitempty"`
	// The longitude of the stop point.
	Longitude *float64 `json:"longitude,omitempty"`
	TariffZone1 *VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel `json:"tariffZone1,omitempty"`
	TariffZone2 *VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel `json:"tariffZone2,omitempty"`
}

// NewVTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel instantiates a new VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel() *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel {
	this := VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel{}
	return &this
}

// NewVTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModelWithDefaults instantiates a new VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModelWithDefaults() *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel {
	this := VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel{}
	return &this
}

// GetGid returns the Gid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) GetGid() string {
	if o == nil || IsNil(o.Gid.Get()) {
		var ret string
		return ret
	}
	return *o.Gid.Get()
}

// GetGidOk returns a tuple with the Gid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) GetGidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Gid.Get(), o.Gid.IsSet()
}

// HasGid returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) HasGid() bool {
	if o != nil && o.Gid.IsSet() {
		return true
	}

	return false
}

// SetGid gets a reference to the given NullableString and assigns it to the Gid field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) SetGid(v string) {
	o.Gid.Set(&v)
}
// SetGidNil sets the value for Gid to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) SetGidNil() {
	o.Gid.Set(nil)
}

// UnsetGid ensures that no value is present for Gid, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) UnsetGid() {
	o.Gid.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) UnsetName() {
	o.Name.Unset()
}

// GetLatitude returns the Latitude field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) GetLatitude() float64 {
	if o == nil || IsNil(o.Latitude) {
		var ret float64
		return ret
	}
	return *o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) GetLatitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Latitude) {
		return nil, false
	}
	return o.Latitude, true
}

// HasLatitude returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) HasLatitude() bool {
	if o != nil && !IsNil(o.Latitude) {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given float64 and assigns it to the Latitude field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) SetLatitude(v float64) {
	o.Latitude = &v
}

// GetLongitude returns the Longitude field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) GetLongitude() float64 {
	if o == nil || IsNil(o.Longitude) {
		var ret float64
		return ret
	}
	return *o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) GetLongitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Longitude) {
		return nil, false
	}
	return o.Longitude, true
}

// HasLongitude returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) HasLongitude() bool {
	if o != nil && !IsNil(o.Longitude) {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given float64 and assigns it to the Longitude field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) SetLongitude(v float64) {
	o.Longitude = &v
}

// GetTariffZone1 returns the TariffZone1 field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) GetTariffZone1() VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel {
	if o == nil || IsNil(o.TariffZone1) {
		var ret VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel
		return ret
	}
	return *o.TariffZone1
}

// GetTariffZone1Ok returns a tuple with the TariffZone1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) GetTariffZone1Ok() (*VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel, bool) {
	if o == nil || IsNil(o.TariffZone1) {
		return nil, false
	}
	return o.TariffZone1, true
}

// HasTariffZone1 returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) HasTariffZone1() bool {
	if o != nil && !IsNil(o.TariffZone1) {
		return true
	}

	return false
}

// SetTariffZone1 gets a reference to the given VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel and assigns it to the TariffZone1 field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) SetTariffZone1(v VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel) {
	o.TariffZone1 = &v
}

// GetTariffZone2 returns the TariffZone2 field value if set, zero value otherwise.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) GetTariffZone2() VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel {
	if o == nil || IsNil(o.TariffZone2) {
		var ret VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel
		return ret
	}
	return *o.TariffZone2
}

// GetTariffZone2Ok returns a tuple with the TariffZone2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) GetTariffZone2Ok() (*VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel, bool) {
	if o == nil || IsNil(o.TariffZone2) {
		return nil, false
	}
	return o.TariffZone2, true
}

// HasTariffZone2 returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) HasTariffZone2() bool {
	if o != nil && !IsNil(o.TariffZone2) {
		return true
	}

	return false
}

// SetTariffZone2 gets a reference to the given VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel and assigns it to the TariffZone2 field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) SetTariffZone2(v VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel) {
	o.TariffZone2 = &v
}

func (o VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Gid.IsSet() {
		toSerialize["gid"] = o.Gid.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if !IsNil(o.Latitude) {
		toSerialize["latitude"] = o.Latitude
	}
	if !IsNil(o.Longitude) {
		toSerialize["longitude"] = o.Longitude
	}
	if !IsNil(o.TariffZone1) {
		toSerialize["tariffZone1"] = o.TariffZone1
	}
	if !IsNil(o.TariffZone2) {
		toSerialize["tariffZone2"] = o.TariffZone2
	}
	return toSerialize, nil
}

type NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel struct {
	value *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel
	isSet bool
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) Get() *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel {
	return v.value
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) Set(val *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel(val *VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) *NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel {
	return &NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel{value: val, isSet: true}
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


