/*
Planera Resa

Sök och planera resor med Västtrafik

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel{}

// VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel Information about an endpoint on an access link.
type VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel struct {
	// The 16-digit Västtrafik gid.
	Gid NullableString `json:"gid,omitempty"`
	// The location name.
	Name string `json:"name"`
	LocationType VTApiPlaneraResaCoreModelsLocationType `json:"locationType"`
	// The WGS84 latitude of the location.
	Latitude NullableFloat64 `json:"latitude,omitempty"`
	// The WGS84 longitude of the location.
	Longitude NullableFloat64 `json:"longitude,omitempty"`
	// The planned time in RFC 3339 format.
	PlannedTime string `json:"plannedTime"`
	// The estimated time in RFC 3339 format.
	EstimatedTime NullableString `json:"estimatedTime,omitempty"`
	// The best known time of the link in RFC 3339 format. Is EstimatedTime if exists, otherwise PlannedTime.
	EstimatedOtherwisePlannedTime NullableString `json:"estimatedOtherwisePlannedTime,omitempty"`
	// An ordered list (most important first) of notes related to the end point.
	Notes []VTApiPlaneraResaCoreModelsNote `json:"notes,omitempty"`
}

// NewVTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel instantiates a new VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel(name string, locationType VTApiPlaneraResaCoreModelsLocationType, plannedTime string) *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel {
	this := VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel{}
	this.Name = name
	this.LocationType = locationType
	this.PlannedTime = plannedTime
	return &this
}

// NewVTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModelWithDefaults instantiates a new VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModelWithDefaults() *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel {
	this := VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel{}
	return &this
}

// GetGid returns the Gid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) GetGid() string {
	if o == nil || IsNil(o.Gid.Get()) {
		var ret string
		return ret
	}
	return *o.Gid.Get()
}

// GetGidOk returns a tuple with the Gid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) GetGidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Gid.Get(), o.Gid.IsSet()
}

// HasGid returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) HasGid() bool {
	if o != nil && o.Gid.IsSet() {
		return true
	}

	return false
}

// SetGid gets a reference to the given NullableString and assigns it to the Gid field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) SetGid(v string) {
	o.Gid.Set(&v)
}
// SetGidNil sets the value for Gid to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) SetGidNil() {
	o.Gid.Set(nil)
}

// UnsetGid ensures that no value is present for Gid, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) UnsetGid() {
	o.Gid.Unset()
}

// GetName returns the Name field value
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) SetName(v string) {
	o.Name = v
}

// GetLocationType returns the LocationType field value
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) GetLocationType() VTApiPlaneraResaCoreModelsLocationType {
	if o == nil {
		var ret VTApiPlaneraResaCoreModelsLocationType
		return ret
	}

	return o.LocationType
}

// GetLocationTypeOk returns a tuple with the LocationType field value
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) GetLocationTypeOk() (*VTApiPlaneraResaCoreModelsLocationType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LocationType, true
}

// SetLocationType sets field value
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) SetLocationType(v VTApiPlaneraResaCoreModelsLocationType) {
	o.LocationType = v
}

// GetLatitude returns the Latitude field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) GetLatitude() float64 {
	if o == nil || IsNil(o.Latitude.Get()) {
		var ret float64
		return ret
	}
	return *o.Latitude.Get()
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) GetLatitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Latitude.Get(), o.Latitude.IsSet()
}

// HasLatitude returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) HasLatitude() bool {
	if o != nil && o.Latitude.IsSet() {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given NullableFloat64 and assigns it to the Latitude field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) SetLatitude(v float64) {
	o.Latitude.Set(&v)
}
// SetLatitudeNil sets the value for Latitude to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) SetLatitudeNil() {
	o.Latitude.Set(nil)
}

// UnsetLatitude ensures that no value is present for Latitude, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) UnsetLatitude() {
	o.Latitude.Unset()
}

// GetLongitude returns the Longitude field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) GetLongitude() float64 {
	if o == nil || IsNil(o.Longitude.Get()) {
		var ret float64
		return ret
	}
	return *o.Longitude.Get()
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) GetLongitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Longitude.Get(), o.Longitude.IsSet()
}

// HasLongitude returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) HasLongitude() bool {
	if o != nil && o.Longitude.IsSet() {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given NullableFloat64 and assigns it to the Longitude field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) SetLongitude(v float64) {
	o.Longitude.Set(&v)
}
// SetLongitudeNil sets the value for Longitude to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) SetLongitudeNil() {
	o.Longitude.Set(nil)
}

// UnsetLongitude ensures that no value is present for Longitude, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) UnsetLongitude() {
	o.Longitude.Unset()
}

// GetPlannedTime returns the PlannedTime field value
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) GetPlannedTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlannedTime
}

// GetPlannedTimeOk returns a tuple with the PlannedTime field value
// and a boolean to check if the value has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) GetPlannedTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlannedTime, true
}

// SetPlannedTime sets field value
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) SetPlannedTime(v string) {
	o.PlannedTime = v
}

// GetEstimatedTime returns the EstimatedTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) GetEstimatedTime() string {
	if o == nil || IsNil(o.EstimatedTime.Get()) {
		var ret string
		return ret
	}
	return *o.EstimatedTime.Get()
}

// GetEstimatedTimeOk returns a tuple with the EstimatedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) GetEstimatedTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EstimatedTime.Get(), o.EstimatedTime.IsSet()
}

// HasEstimatedTime returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) HasEstimatedTime() bool {
	if o != nil && o.EstimatedTime.IsSet() {
		return true
	}

	return false
}

// SetEstimatedTime gets a reference to the given NullableString and assigns it to the EstimatedTime field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) SetEstimatedTime(v string) {
	o.EstimatedTime.Set(&v)
}
// SetEstimatedTimeNil sets the value for EstimatedTime to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) SetEstimatedTimeNil() {
	o.EstimatedTime.Set(nil)
}

// UnsetEstimatedTime ensures that no value is present for EstimatedTime, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) UnsetEstimatedTime() {
	o.EstimatedTime.Unset()
}

// GetEstimatedOtherwisePlannedTime returns the EstimatedOtherwisePlannedTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) GetEstimatedOtherwisePlannedTime() string {
	if o == nil || IsNil(o.EstimatedOtherwisePlannedTime.Get()) {
		var ret string
		return ret
	}
	return *o.EstimatedOtherwisePlannedTime.Get()
}

// GetEstimatedOtherwisePlannedTimeOk returns a tuple with the EstimatedOtherwisePlannedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) GetEstimatedOtherwisePlannedTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EstimatedOtherwisePlannedTime.Get(), o.EstimatedOtherwisePlannedTime.IsSet()
}

// HasEstimatedOtherwisePlannedTime returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) HasEstimatedOtherwisePlannedTime() bool {
	if o != nil && o.EstimatedOtherwisePlannedTime.IsSet() {
		return true
	}

	return false
}

// SetEstimatedOtherwisePlannedTime gets a reference to the given NullableString and assigns it to the EstimatedOtherwisePlannedTime field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) SetEstimatedOtherwisePlannedTime(v string) {
	o.EstimatedOtherwisePlannedTime.Set(&v)
}
// SetEstimatedOtherwisePlannedTimeNil sets the value for EstimatedOtherwisePlannedTime to be an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) SetEstimatedOtherwisePlannedTimeNil() {
	o.EstimatedOtherwisePlannedTime.Set(nil)
}

// UnsetEstimatedOtherwisePlannedTime ensures that no value is present for EstimatedOtherwisePlannedTime, not even an explicit nil
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) UnsetEstimatedOtherwisePlannedTime() {
	o.EstimatedOtherwisePlannedTime.Unset()
}

// GetNotes returns the Notes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) GetNotes() []VTApiPlaneraResaCoreModelsNote {
	if o == nil {
		var ret []VTApiPlaneraResaCoreModelsNote
		return ret
	}
	return o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) GetNotesOk() ([]VTApiPlaneraResaCoreModelsNote, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) HasNotes() bool {
	if o != nil && IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given []VTApiPlaneraResaCoreModelsNote and assigns it to the Notes field.
func (o *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) SetNotes(v []VTApiPlaneraResaCoreModelsNote) {
	o.Notes = v
}

func (o VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Gid.IsSet() {
		toSerialize["gid"] = o.Gid.Get()
	}
	toSerialize["name"] = o.Name
	toSerialize["locationType"] = o.LocationType
	if o.Latitude.IsSet() {
		toSerialize["latitude"] = o.Latitude.Get()
	}
	if o.Longitude.IsSet() {
		toSerialize["longitude"] = o.Longitude.Get()
	}
	toSerialize["plannedTime"] = o.PlannedTime
	if o.EstimatedTime.IsSet() {
		toSerialize["estimatedTime"] = o.EstimatedTime.Get()
	}
	if o.EstimatedOtherwisePlannedTime.IsSet() {
		toSerialize["estimatedOtherwisePlannedTime"] = o.EstimatedOtherwisePlannedTime.Get()
	}
	if o.Notes != nil {
		toSerialize["notes"] = o.Notes
	}
	return toSerialize, nil
}

type NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel struct {
	value *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel
	isSet bool
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) Get() *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel {
	return v.value
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) Set(val *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel(val *VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) *NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel {
	return &NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel{value: val, isSet: true}
}

func (v NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


